user_pref("dom.disable_window_flip", false)
user_pref("dom.disable_window_move_resize", false)
user_pref("dom.event.clipboardevents.enabled", false)
user_pref("geo.enabled", false)
user_pref("media.peerconnection.enabled", false)
user_pref("media.video_stats.enabled", false)
user_pref("plugin.state.flash", 0)
