--Keymapping function
local map = vim.api.nvim_set_keymap

-- nvim-dap (debugging)
map('n', '<leader>c', ':lua require("dap").continue()<CR>', {noremap = true})
map('n', '<leader>n', ':lua require("dap").step_over()<CR>', {noremap = true})
map('n', '<leader>.', ':lua require("dap").step_into()<CR>', {noremap = true})
map('n', '<leader>,', ':lua require("dap").step_out()<CR>', {noremap = true})
map('n', '<leader>b', ':lua require("dap").toggle_breakpoint()<CR>', {noremap = true})
map('n', '<leader>o', ':lua require("dap").repl.open()<CR>', {noremap = true})
map('n', '<leader>v', ':lua require("dap").repl.run_last()<CR>', {noremap = true})

-- telescope (fuzzy finder)
map('n', '<leader>ff', ':lua require("telescope.builtin").find_files()<cr>', {noremap = true})
map('n', '<leader>fg', ':lua require("telescope.builtin").live_grep()<cr>', {noremap = true})
map('n', '<leader>fb', ':lua require("telescope.builtin").buffers()<cr>', {noremap = true})
map('n', '<leader>fh', ':lua require("telescope.builtin").help_tags()<cr>', {noremap = true})

-- barbar (top bar)
map('n', '<A-,>', ':BufferPrevious<CR>', { noremap = true })
map('n', '<A-.>', ':BufferNext<CR>', { noremap = true })
map('n', '<A-<>', ':BufferMovePrevious<CR>', { noremap = true })
map('n', '<A->>', ' :BufferMoveNext<CR>', { noremap = true })
map('n', '<A-1>', ':BufferGoto 1<CR>', { noremap = true })
map('n', '<A-2>', ':BufferGoto 2<CR>', { noremap = true })
map('n', '<A-3>', ':BufferGoto 3<CR>', { noremap = true })
map('n', '<A-4>', ':BufferGoto 4<CR>', { noremap = true })
map('n', '<A-5>', ':BufferGoto 5<CR>', { noremap = true })
map('n', '<A-6>', ':BufferGoto 6<CR>', { noremap = true })
map('n', '<A-7>', ':BufferGoto 7<CR>', { noremap = true })
map('n', '<A-8>', ':BufferGoto 8<CR>', { noremap = true })
map('n', '<A-9>', ':BufferGoto 9<CR>', { noremap = true })
map('n', '<A-0>', ':BufferLast<CR>', { noremap = true })
map('n', '<A-c>', ':BufferClose<CR>', { noremap = true })
map('n', '<Space>bb', ':BufferOrderByBufferNumber<CR>', { noremap = true })
map('n', '<Space>bd', ':BufferOrderByDirectory<CR>', { noremap = true })
map('n', '<Space>bl', ':BufferOrderByLanguage<CR>', { noremap = true })

-- trouble.nvim (linting stuff)
map('n', '<leader>xx', ':Trouble<cr>', { noremap = true })
map('n', '<leader>xw', ':Trouble workspace_diagnostics<cr>', { noremap = true })
map('n', '<leader>xd', ':Trouble document_diagnostics<cr>', { noremap = true })
map('n', '<leader>xl', ':Trouble loglist<cr>', { noremap = true })
map('n', '<leader>xq', ':Trouble quickfix<cr>', { noremap = true })
map('n', '<leader>gR', ':Trouble lsp_references<cr>', { noremap = true })
map('n', '<leader>x,', ':lua require("trouble").previous({skip_groups = true, jump = true})<cr>', { noremap = true })
map('n', '<leader>x.', ':lua require("trouble").next({skip_groups = true, jump = true})<cr>', { noremap = true })

-- null-ls.nvim (formatting)
map('n', 'fmt', ':lua vim.lsp.buf.format {async = true}<CR>', {noremap = true})
